2024-04-14 14:19:31,529 INFO    MainThread:31235 [wandb_setup.py:_flush():68] setting env: {}
2024-04-14 14:19:31,529 INFO    MainThread:31235 [wandb_setup.py:_flush():68] multiprocessing start_methods=fork,spawn,forkserver
2024-04-14 14:19:31,529 INFO    MainThread:31235 [wandb_setup.py:_flush():68] setting login settings: {}
2024-04-14 14:19:31,530 INFO    MainThread:31235 [wandb_init.py:_log_setup():301] Logging user logs to wandb/run-20240414_141931-fopqmnln/logs/debug.log
2024-04-14 14:19:31,530 INFO    MainThread:31235 [wandb_init.py:_log_setup():302] Logging internal logs to wandb/run-20240414_141931-fopqmnln/logs/debug-internal.log
2024-04-14 14:19:32,373 INFO    MainThread:31235 [wandb_run.py:_console_start():1322] atexit reg
2024-04-14 14:19:32,374 INFO    MainThread:31235 [wandb_run.py:_redirect():1192] redirect: SettingsConsole.REDIRECT
2024-04-14 14:19:32,375 INFO    MainThread:31235 [wandb_run.py:_redirect():1195] Redirecting console.
2024-04-14 14:19:32,375 INFO    MainThread:31235 [redirect.py:install():204] install start
2024-04-14 14:19:32,375 INFO    MainThread:31235 [redirect.py:install():219] install stop
2024-04-14 14:19:32,375 INFO    MainThread:31235 [redirect.py:install():204] install start
2024-04-14 14:19:32,375 INFO    MainThread:31235 [redirect.py:install():219] install stop
2024-04-14 14:19:32,375 INFO    MainThread:31235 [wandb_run.py:_redirect():1239] Redirects installed.
2024-04-14 14:19:32,389 INFO    MainThread:31235 [wandb_run.py:_config_callback():654] config_cb None None {'imba': False, 'model_name': 'DANN', 'Domain': 'SEU', 'source': 'SEU_1', 'target': 'SEU_0', 'data_dir': '/home/workspace/UDA_Bearing_Fault_Diagnosis/datasets', 'train_mode': 'single_source', 'cuda_device': '0', 'save_dir': './ckpt', 'max_epoch': 100, 'batch_size': 64, 'num_workers': 0, 'signal_size': 2048, 'random_state': 75, 'normlizetype': 'mean-std', 'opt': 'sgd', 'lr': 0.001, 'momentum': 0.9, 'betas': [0.9, 0.999], 'weight_decay': 0.0005, 'lr_scheduler': 'stepLR', 'gamma': 0.2, 'steps': '10', 'tradeoff': ['exp', 'exp', 'exp'], 'dropout': 0.0, 'save': False, 'load_path': '', 'tsne': False, '_wandb': {'cli_version': '0.10.9', 'python_version': '3.6.9', 'is_jupyter_run': False, 'is_kaggle_kernel': False, 'framework': 'torch'}}
2024-04-14 14:19:39,248 INFO    MainThread:31235 [wandb_run.py:_atexit_cleanup():1295] got exitcode: 1
2024-04-14 14:19:39,248 INFO    MainThread:31235 [wandb_run.py:_restore():1267] restore
2024-04-14 14:19:39,248 INFO    MainThread:31235 [redirect.py:uninstall():223] uninstall start
2024-04-14 14:19:39,249 INFO    MainThread:31235 [redirect.py:_stop():278] _stop: stdout
2024-04-14 14:19:39,249 INFO    MainThread:31235 [redirect.py:_stop():284] _stop closed: stdout
2024-04-14 14:19:39,249 INFO    stdout    :31235 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2024-04-14 14:19:39,249 INFO    stdout    :31235 [redirect.py:_pipe_relay():136] relay done done: stdout
2024-04-14 14:19:39,250 INFO    MainThread:31235 [redirect.py:_stop():290] _stop joined: stdout
2024-04-14 14:19:39,250 INFO    MainThread:31235 [redirect.py:_stop():292] _stop rd closed: stdout
2024-04-14 14:19:39,250 INFO    MainThread:31235 [redirect.py:uninstall():227] uninstall done
2024-04-14 14:19:39,250 INFO    MainThread:31235 [redirect.py:uninstall():223] uninstall start
2024-04-14 14:19:39,250 INFO    MainThread:31235 [redirect.py:_stop():278] _stop: stderr
2024-04-14 14:19:39,250 INFO    stderr    :31235 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2024-04-14 14:19:39,250 INFO    MainThread:31235 [redirect.py:_stop():284] _stop closed: stderr
2024-04-14 14:19:39,250 INFO    stderr    :31235 [redirect.py:_pipe_relay():136] relay done done: stderr
2024-04-14 14:19:39,250 INFO    MainThread:31235 [redirect.py:_stop():290] _stop joined: stderr
2024-04-14 14:19:39,250 INFO    MainThread:31235 [redirect.py:_stop():292] _stop rd closed: stderr
2024-04-14 14:19:39,250 INFO    MainThread:31235 [redirect.py:uninstall():227] uninstall done
2024-04-14 14:19:39,252 INFO    MainThread:31235 [wandb_run.py:_wait_for_finish():1409] got exit ret: uuid: "961bb82323144135bcdf44b6225cbf3f"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 771
      total_bytes: 771
    }
  }
}

2024-04-14 14:19:41,255 INFO    MainThread:31235 [wandb_run.py:_wait_for_finish():1409] got exit ret: uuid: "4facc792049b4270ad40a3e37efedac6"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 7488
      total_bytes: 7488
    }
  }
}

2024-04-14 14:19:42,311 INFO    MainThread:31235 [wandb_run.py:_show_files():1618] logging synced files
2024-04-14 14:19:42,313 INFO    MainThread:31235 [internal.py:handle_exit():138] Internal process exited
